import { StyleSheet } from "react-native";

export const colors = {
  background: "#F6F7F2",
  ink: "#182C25",
  muted: "#66756D",
  green: "#236B4B",
  light: "#E7EFE7",
  border: "#DFE5DD",
  red: "#AF3831",
};
export const styles = StyleSheet.create({
  page: { flex: 1, backgroundColor: colors.background },
  content: { padding: 24, gap: 22, paddingBottom: 40 },
  row: { flexDirection: "row", alignItems: "center", gap: 12 },
  between: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  title: { fontSize: 30, fontWeight: "800", color: colors.ink },
  heading: { fontSize: 20, fontWeight: "700", color: colors.ink },
  text: { fontSize: 16, color: colors.ink },
  muted: { fontSize: 14, color: colors.muted, lineHeight: 21 },
  eyebrow: {
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 2,
    color: colors.green,
  },
  card: {
    padding: 20,
    borderRadius: 22,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: colors.border,
    gap: 16,
  },
  button: {
    backgroundColor: colors.green,
    paddingVertical: 15,
    paddingHorizontal: 20,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    minHeight: 48,
  },
  buttonText: { color: "white", fontWeight: "700", fontSize: 16 },
  link: { color: colors.green, fontSize: 14, fontWeight: "700" },
  input: {
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 12,
    padding: 14,
    fontSize: 16,
    color: colors.ink,
    backgroundColor: "#FFFFFF",
    minHeight: 50,
  },
  label: {
    fontSize: 14,
    fontWeight: "600",
    color: colors.ink,
    marginBottom: 8,
  },
  error: { color: colors.red, fontSize: 14, lineHeight: 21 },
  center: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 28,
    gap: 18,
  },
});
